import logging
from pathlib import Path
from typing import Final

from agent_sync.configuration import AgentSyncConfigError
from agent_sync.markdown import (
    ensure_trailing_newline,
    normalize_rule_source,
    parse_markdown_file,
    validate_slug,
)
from agent_sync.models.configuration import Provider, Workspace
from agent_sync.models.documents import RuleFrontMatter, SkillFrontMatter
from agent_sync.models.outputs import OutputFile, OutputKind

__all__ = [
    "assemble_universal_agent_instructions",
    "generate_rule_outputs",
    "generate_skill_outputs",
]

logger = logging.getLogger(__name__)

CODEX_RULE_MARKER: Final[str] = "# Generated by agent_sync from .agents/rules/"


def generate_skill_outputs(workspace: Workspace) -> list[OutputFile]:
    """Generate provider skill links from canonical skill directories."""

    skills_dir = workspace.agents / "skills"

    if not skills_dir.exists():
        return []

    outputs: list[OutputFile] = []
    for skill_dir in sorted(path for path in skills_dir.iterdir() if path.is_dir()):
        slug = validate_slug(skill_dir.name, skill_dir)
        source_path = skill_dir / "SKILL.md"

        if not source_path.exists():
            logger.warning("Missing SKILL.md in %s", skill_dir)
            continue

        front_matter, _ = parse_markdown_file(source_path, SkillFrontMatter)
        validate_canonical_skill_metadata(front_matter, source_path)
        outputs.extend(
            OutputFile(
                target_path=workspace.root / f".{provider.value}" / "skills" / slug,
                content="",
                kind=skill_link_kind(provider),
                slug=slug,
                source_path=source_path,
                link_target=skill_dir,
            )
            for provider in (Provider.CLAUDE, Provider.CURSOR)
        )
        outputs.append(
            OutputFile(
                target_path=workspace.root / ".codex" / "skills" / slug,
                content="",
                kind=OutputKind.CODEX_SKILL,
                slug=slug,
                source_path=source_path,
                link_target=skill_dir,
            )
        )

    return outputs


def validate_canonical_skill_metadata(
    front_matter: SkillFrontMatter,
    source_path: Path,
) -> None:
    """Require metadata shared by every canonical skill."""

    if not front_matter.name or not front_matter.description:
        raise AgentSyncConfigError(
            f"Skill {source_path} must define non-empty name and description front matter"
        )

    if front_matter.name != source_path.parent.name:
        raise AgentSyncConfigError(
            f"Skill {source_path} must use directory name {source_path.parent.name!r} "
            f"as its front matter name, not {front_matter.name!r}"
        )


def skill_link_kind(provider: Provider) -> OutputKind:
    """Return the directory-link output kind for one provider."""

    match provider:
        case Provider.CLAUDE:
            return OutputKind.CLAUDE_SKILL
        case Provider.CURSOR:
            return OutputKind.CURSOR_SKILL
        case Provider.CODEX:
            raise ValueError("Codex skills use their dedicated directory-link output")


def generate_rule_outputs(workspace: Workspace) -> list[OutputFile]:
    """Generate normalized canonical rules and provider mirrors."""

    rules_dir = workspace.agents / "rules"

    if not rules_dir.exists():
        return []

    outputs: list[OutputFile] = []
    for path in sorted(rules_dir.glob("*.md")):
        slug = validate_slug(path.stem, path)
        front_matter, body = parse_markdown_file(path, RuleFrontMatter)
        if body:
            outputs.append(
                OutputFile(
                    target_path=path,
                    content=normalize_rule_source(front_matter, body),
                    kind=OutputKind.AGENTS_RULE,
                    slug=slug,
                    source_path=path,
                )
            )
            outputs.extend(generate_rule_links(workspace, path, slug))
        if front_matter.starlark:
            outputs.append(
                OutputFile(
                    target_path=workspace.root / ".codex" / "rules" / f"{slug}.rules",
                    content=ensure_trailing_newline(
                        f"{CODEX_RULE_MARKER}{path.name}\n{front_matter.starlark.strip()}"
                    ),
                    kind=OutputKind.CODEX_RULE,
                    slug=slug,
                    source_path=path,
                )
            )

    return outputs


def generate_rule_links(workspace: Workspace, source_path: Path, slug: str) -> list[OutputFile]:
    """Generate Claude and Cursor rule links."""

    return [
        OutputFile(
            target_path=(
                workspace.root
                / f".{provider.value}"
                / "rules"
                / (f"{slug}.md" if provider is Provider.CLAUDE else f"{slug}.mdc")
            ),
            content="",
            kind=(OutputKind.CLAUDE_RULE if provider is Provider.CLAUDE else OutputKind.CURSOR_RULE),
            slug=slug,
            source_path=source_path,
            link_target=source_path,
        )
        for provider in (Provider.CLAUDE, Provider.CURSOR)
    ]


def assemble_universal_agent_instructions(workspace: Workspace) -> str:
    """Combine canonical rules into Universal Agent Instructions."""

    header = (
        "# AGENTS.md\n\n"
        "Generated by `.github/scripts/agent_sync/main.py`. Do not edit this file directly.\n\n"
        "The canonical project rules live in `.agents/rules/`.\n"
    )
    rules_dir = workspace.agents / "rules"

    if not rules_dir.exists():
        return ensure_trailing_newline(header)

    sections = [
        render_rule_section(path.name, front_matter, body)
        for path in sorted(rules_dir.glob("*.md"))
        for front_matter, body in [parse_markdown_file(path, RuleFrontMatter)]
        if body
    ]

    return ensure_trailing_newline(header if not sections else header + "\n" + "\n\n".join(sections))


def render_rule_section(filename: str, front_matter: RuleFrontMatter, body: str) -> str:
    """Render one canonical rule section with its applicability note."""

    source = f"<!-- Source: .agents/rules/{filename} -->"
    scope = render_rule_scope(front_matter)

    return "\n\n".join(part for part in (source, scope, body) if part)


def render_rule_scope(front_matter: RuleFrontMatter) -> str:
    """Render the universal applicability note for one rule."""

    patterns = [front_matter.globs] if isinstance(front_matter.globs, str) else front_matter.globs or []

    if patterns:
        rendered_patterns = ", ".join(f"`{pattern}`" for pattern in patterns)

        return f"> Applies only to files matching: {rendered_patterns}"
    if not front_matter.always_apply:
        return "> Apply this rule only when it is explicitly relevant to the current task."

    return ""
