from pathlib import Path
from typing import Final

from agent_sync.markdown import (
    ensure_trailing_newline,
    normalize_rule_source,
    parse_markdown_file,
    validate_slug,
)
from agent_sync.models.frontmatter import RuleFrontMatter
from agent_sync.models.outputs import OutputFile, OutputKind
from agent_sync.models.providers.providers import Provider
from agent_sync.models.workspace import Workspace

__all__ = [
    "assemble_universal_agent_instructions",
    "generate_rule_outputs",
    "is_managed_codex_rule",
]

CODEX_RULE_MARKER: Final[str] = "# Generated by agent_sync from .agents/rules/"


def generate_rule_outputs(workspace: Workspace) -> list[OutputFile]:
    """Generate normalized canonical rules and provider mirrors."""

    rules_dir = workspace.agents / "rules"

    if not rules_dir.exists():
        return []

    outputs: list[OutputFile] = []
    for path in sorted(rules_dir.glob("*.md")):
        slug = validate_slug(path.stem, path)
        front_matter, body = parse_markdown_file(path, RuleFrontMatter)
        if body:
            outputs.append(
                OutputFile(
                    target_path=path,
                    content=normalize_rule_source(front_matter, body),
                    kind=OutputKind.AGENTS_RULE,
                    slug=slug,
                    source_path=path,
                )
            )
            outputs.extend(generate_rule_links(workspace, path, slug))
        if front_matter.starlark:
            outputs.append(
                OutputFile(
                    target_path=workspace.root / ".codex" / "rules" / f"{slug}.rules",
                    content=ensure_trailing_newline(
                        f"{CODEX_RULE_MARKER}{path.name}\n{front_matter.starlark.strip()}"
                    ),
                    kind=OutputKind.CODEX_RULE,
                    slug=slug,
                    source_path=path,
                )
            )

    return outputs


def generate_rule_links(workspace: Workspace, source_path: Path, slug: str) -> list[OutputFile]:
    """Generate Claude and Cursor rule links."""

    return [
        OutputFile(
            target_path=(
                workspace.root
                / f".{provider.value}"
                / "rules"
                / (f"{slug}.md" if provider is Provider.CLAUDE else f"{slug}.mdc")
            ),
            content="",
            kind=(OutputKind.CLAUDE_RULE if provider is Provider.CLAUDE else OutputKind.CURSOR_RULE),
            slug=slug,
            source_path=source_path,
            link_target=source_path,
        )
        for provider in (Provider.CLAUDE, Provider.CURSOR)
    ]


def assemble_universal_agent_instructions(workspace: Workspace) -> str:
    """Combine canonical rules into Universal Agent Instructions."""

    header = (
        "# AGENTS.md\n\n"
        "Generated by `.github/scripts/agent_sync/main.py`. Do not edit this file directly.\n\n"
        "The canonical project rules live in `.agents/rules/`.\n"
    )
    rules_dir = workspace.agents / "rules"

    if not rules_dir.exists():
        return ensure_trailing_newline(header)

    sections = [
        render_rule_section(path.name, front_matter, body)
        for path in sorted(rules_dir.glob("*.md"))
        for front_matter, body in [parse_markdown_file(path, RuleFrontMatter)]
        if body
    ]

    return ensure_trailing_newline(header if not sections else header + "\n" + "\n\n".join(sections))


def render_rule_section(filename: str, front_matter: RuleFrontMatter, body: str) -> str:
    """Render one canonical rule section with its applicability note."""

    source = f"<!-- Source: .agents/rules/{filename} -->"
    scope = render_rule_scope(front_matter)

    return "\n\n".join(part for part in (source, scope, body) if part)


def render_rule_scope(front_matter: RuleFrontMatter) -> str:
    """Render the Codex applicability note for one rule."""

    if isinstance(front_matter.globs, str):
        patterns = [front_matter.globs]
    else:
        patterns = front_matter.globs or []

    if patterns:
        rendered_patterns = ", ".join(f"`{pattern}`" for pattern in patterns)

        return f"> Applies only to files matching: {rendered_patterns}"
    if not front_matter.always_apply:
        return "> Apply this rule only when it is explicitly relevant to the current task."

    return ""


def is_managed_codex_rule(content: str) -> bool:
    """Return whether a Starlark policy was generated by agent sync."""

    return content.startswith(CODEX_RULE_MARKER)
